# <--------- Session-9 --------->

Task.1 :- Given a list of delivery timestamps as strings (e.g., ['2024-06-01 14:30', '2024-06-02 09:15', '2024-06-03 20:45']), use pandas and pd.to_datetime() to convert them into datetime objects and print the result.

In [3]:
import pandas as pd

In [5]:
list = ['2024-06-01 14:30', '2024-06-02 09:15', '2024-06-03 20:45']

df1 = pd.to_datetime(list)
df1

DatetimeIndex(['2024-06-01 14:30:00', '2024-06-02 09:15:00',
               '2024-06-03 20:45:00'],
              dtype='datetime64[us]', freq=None)

Task.2 :- Load a CSV file containing order dates from a Flipkart-style order history (column: 'order_date', format: 'YYYY-MM-DD HH:MM:SS'). Extract the year, month, and weekday for each order and add them as new columns in the DataFrame.

In [27]:
df2 = pd.read_csv("flipcartstyle.csv")
df2

   order_id customer_name           order_date  amount
0       101          Amit  2026-06-20 10:30:45    1299
1       102         Priya  2026-06-21 14:15:20     799
2       103         Rahul  2026-06-22 09:45:10    2499
3       104          Neha  2026-06-23 18:20:55    1599
4       105         Rohan  2026-06-24 11:10:30     999

In [28]:
df2["order_date"] = pd.to_datetime(df2["order_date"])

In [29]:
df2["Year"] = df2["order_date"].dt.year
df2["Month"] = df2["order_date"].dt.month
df2["Date"] = df2["order_date"].dt.day
df2["Day"] = df2["order_date"].dt.weekday
df2

   order_id customer_name          order_date  amount  Year  Month  Date  Day
0       101          Amit 2026-06-20 10:30:45    1299  2026      6    20    5
1       102         Priya 2026-06-21 14:15:20     799  2026      6    21    6
2       103         Rahul 2026-06-22 09:45:10    2499  2026      6    22    0
3       104          Neha 2026-06-23 18:20:55    1599  2026      6    23    1
4       105         Rohan 2026-06-24 11:10:30     999  2026      6    24    2

Task.3 :- Set the 'order_date' column as the index of your DataFrame and use resampling to calculate the total number of orders placed each week.<br><br><em><strong>Hint:</strong> Use df.resample('W').size() after setting the datetime index.</em>

In [41]:
df3 = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106, 107],
    "order_date": [
        "2026-06-01 10:30:45",
        "2026-06-03 14:15:20",
        "2026-06-08 09:45:10",
        "2026-06-10 18:20:55",
        "2026-06-15 11:10:30",
        "2026-06-16 16:45:00",
        "2026-06-22 12:20:15"
    ]
})
df3["order_date"] = pd.to_datetime(df3["order_date"])
df3.set_index("order_date", inplace = True)
df3

                     order_id
order_date
2026-06-01 10:30:45       101
2026-06-03 14:15:20       102
2026-06-08 09:45:10       103
2026-06-10 18:20:55       104
2026-06-15 11:10:30       105
2026-06-16 16:45:00       106
2026-06-22 12:20:15       107

In [43]:
df3.resample("W").size()

order_date
2026-06-07    2
2026-06-14    2
2026-06-21    2
2026-06-28    1
Freq: W-SUN, dtype: int64

Task.4 :- Suppose you have a DataFrame of Instagram posts with a 'posted_at' column in UTC. Convert these timestamps to 'Asia/Kolkata' timezone and display the first 5 converted times.

In [52]:
df4 = pd.DataFrame({
    "username": ["alice", "bob", "charlie", "david", "eva","param","hari","meet"],
    "posted_at": [
        "2026-06-20 08:30:00+00:00",
        "2026-06-21 12:45:00+00:00",
        "2026-06-22 16:15:00+00:00",
        "2026-06-23 20:00:00+00:00",
        "2026-06-24 06:10:00+00:00",
        "2026-06-25 16:15:00+00:00",
        "2026-06-26 20:00:00+00:00",
        "2026-06-27 06:10:00+00:00"
    ]
})
df4

  username                  posted_at
0    alice  2026-06-20 08:30:00+00:00
1      bob  2026-06-21 12:45:00+00:00
2  charlie  2026-06-22 16:15:00+00:00
3    david  2026-06-23 20:00:00+00:00
4      eva  2026-06-24 06:10:00+00:00
5    param  2026-06-25 16:15:00+00:00
6     hari  2026-06-26 20:00:00+00:00
7     meet  2026-06-27 06:10:00+00:00

In [53]:
df4["posted_at"] = pd.to_datetime(df4["posted_at"], utc = True)
df4["posted_at"].head(5)

0   2026-06-20 08:30:00+00:00
1   2026-06-21 12:45:00+00:00
2   2026-06-22 16:15:00+00:00
3   2026-06-23 20:00:00+00:00
4   2026-06-24 06:10:00+00:00
Name: posted_at, dtype: datetime64[us, UTC]

Task.5 :- Create a new feature called 'is_weekend' in your DataFrame that marks True if an order was placed on Saturday or Sunday, and False otherwise.<br><br><em><strong>Constraint:</strong> Do not use any external libraries except pandas and numpy.</em>

In [57]:
df5 = pd.DataFrame({
    "username": ["alice", "bob", "charlie", "david", "eva","param","hari","meet"],
    "date": [
        "2026-06-20 08:30:00",
        "2026-06-21 12:45:00",
        "2026-06-22 16:15:00",
        "2026-06-23 20:00:00",
        "2026-06-24 06:10:00",
        "2026-06-25 16:15:00",
        "2026-06-26 20:00:00",
        "2026-06-27 06:10:00"
    ]
})
df5

  username                 date
0    alice  2026-06-20 08:30:00
1      bob  2026-06-21 12:45:00
2  charlie  2026-06-22 16:15:00
3    david  2026-06-23 20:00:00
4      eva  2026-06-24 06:10:00
5    param  2026-06-25 16:15:00
6     hari  2026-06-26 20:00:00
7     meet  2026-06-27 06:10:00

In [ ]:
df5["date"] = pd.to_datetime(df5["date"])

In [61]:
df5["check"]= df5["date"].dt.weekday > 4 
df5

  username                date  check
0    alice 2026-06-20 08:30:00   True
1      bob 2026-06-21 12:45:00   True
2  charlie 2026-06-22 16:15:00  False
3    david 2026-06-23 20:00:00  False
4      eva 2026-06-24 06:10:00  False
5    param 2026-06-25 16:15:00  False
6     hari 2026-06-26 20:00:00  False
7     meet 2026-06-27 06:10:00   True