# <--------- Session-5 --------->

In [3]:
import pandas as pd

Task.1 :- Download a sample CSV file of IPL player stats (include columns like player name, runs, matches, and some missing values). Load it into a pandas DataFrame and use isnull() and notnull() to print how many missing values are present in each column.

In [4]:
a = pd.read_csv(r"C:\PYTHON\Assignments-\Libraries\Session-6\IPL dataset final.csv")
a

,Player,COUNTRY,TEAM,AGE,CAPTAINCY EXP,Paying_Role,Mat,Inns,Runs,BF,...,B_TBalls,B_TRuns,B_TMaidens,B_TWkts,B_TAvg,B_TEcon,B_TSR,B_T4w,B_T5w,SOLD_PRICE
0,Ruturaj Gaikwad,IND,CSK,26,0,Batting,36,36.0,1207.0,926.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6cr
1,Shivam Dube,IND,CSK,29,0,All rounder,35,33.0,688.0,516.0,...,129.0,216.0,0.0,5.0,43.20,10.05,25.80,0.0,0.0,4cr
2,Ambati Rayudu,IND,CSK,37,0,Batting,188,175.0,4190.0,3296.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.75cr
3,Devon Conway,NZ,CSK,31,0,Batting,7,7.0,252.0,173.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1cr
4,Moeen Ali,ENG,CSK,35,0,All rounder,44,42.0,910.0,632.0,...,829.0,1145.0,1.0,42.0,27.26,8.29,19.74,0.0,0.0,8cr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,Abdul Samad,IND,SRH,21,0,All rounder,25,20.0,226.0,159.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4cr
178,Umran Malik,IND,SRH,23,0,Bowling,17,NaN,NaN,NaN,...,139.0,243.0,0.0,11.0,22.09,10.49,12.64,0.0,0.0,4cr
179,Fazalhaq Farooqi,AFG,SRH,22,0,Bowling,3,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50l
180,Jagadeesha Suchith,IND,SRH,29,0,All rounder,22,10.0,70.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20l
181,T Natarajan,IND,SRH,31,0,Bowling,35,NaN,NaN,NaN,...,96.0,122.0,0.0,7.0,17.43,7.62,13.71,0.0,0.0,4cr

In [9]:
a.isnull().sum()

Player             0
COUNTRY            0
TEAM               0
AGE                0
CAPTAINCY EXP      0
Paying_Role        0
Mat                0
Inns              57
Runs              57
BF                57
HS                57
Avg               56
SR                57
NO                57
4s                57
6s                57
0s                58
50s               58
100s              58
TMat              64
TInns            102
TRuns            102
TBF              102
THS              102
TAvg             102
TSR              102
TNO              102
T4s              102
T6s              102
T0s              102
T50s             102
T100s            102
B_Inns            67
B_Balls           68
B_Runs            67
B_Maidens         68
B_Wkts            67
B_Avg             67
B_Econ            67
B_SR              67
B_4w              67
B_5w              67
B_TInns          104
B_TBalls         104
B_TRuns          104
B_TMaidens       104
B_TWkts          104
B_TAvg           104
B_TEcon          104
B_TSR            104
B_T4w            104
B_T5w            105
SOLD_PRICE         0
dtype: int64

In [10]:
a.notnull().sum()

Player           182
COUNTRY          182
TEAM             182
AGE              182
CAPTAINCY EXP    182
Paying_Role      182
Mat              182
Inns             125
Runs             125
BF               125
HS               125
Avg              126
SR               125
NO               125
4s               125
6s               125
0s               124
50s              124
100s             124
TMat             118
TInns             80
TRuns             80
TBF               80
THS               80
TAvg              80
TSR               80
TNO               80
T4s               80
T6s               80
T0s               80
T50s              80
T100s             80
B_Inns           115
B_Balls          114
B_Runs           115
B_Maidens        114
B_Wkts           115
B_Avg            115
B_Econ           115
B_SR             115
B_4w             115
B_5w             115
B_TInns           78
B_TBalls          78
B_TRuns           78
B_TMaidens        78
B_TWkts           78
B_TAvg            78
B_TEcon           78
B_TSR             78
B_T4w             78
B_T5w             77
SOLD_PRICE       182
dtype: int64

Task. 2 :- Using the loaded IPL player stats DataFrame, apply dropna(axis=0, how='any') to remove all rows with any missing data and display the shape of the DataFrame before and after dropping.

In [22]:
a = pd.read_csv(r"C:\PYTHON\Assignments-\Libraries\Session-6\IPL dataset final.csv")
a

,Player,COUNTRY,TEAM,AGE,CAPTAINCY EXP,Paying_Role,Mat,Inns,Runs,BF,...,B_TBalls,B_TRuns,B_TMaidens,B_TWkts,B_TAvg,B_TEcon,B_TSR,B_T4w,B_T5w,SOLD_PRICE
0,Ruturaj Gaikwad,IND,CSK,26,0,Batting,36,36.0,1207.0,926.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6cr
1,Shivam Dube,IND,CSK,29,0,All rounder,35,33.0,688.0,516.0,...,129.0,216.0,0.0,5.0,43.20,10.05,25.80,0.0,0.0,4cr
2,Ambati Rayudu,IND,CSK,37,0,Batting,188,175.0,4190.0,3296.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.75cr
3,Devon Conway,NZ,CSK,31,0,Batting,7,7.0,252.0,173.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1cr
4,Moeen Ali,ENG,CSK,35,0,All rounder,44,42.0,910.0,632.0,...,829.0,1145.0,1.0,42.0,27.26,8.29,19.74,0.0,0.0,8cr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,Abdul Samad,IND,SRH,21,0,All rounder,25,20.0,226.0,159.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4cr
178,Umran Malik,IND,SRH,23,0,Bowling,17,NaN,NaN,NaN,...,139.0,243.0,0.0,11.0,22.09,10.49,12.64,0.0,0.0,4cr
179,Fazalhaq Farooqi,AFG,SRH,22,0,Bowling,3,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50l
180,Jagadeesha Suchith,IND,SRH,29,0,All rounder,22,10.0,70.0,61.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20l
181,T Natarajan,IND,SRH,31,0,Bowling,35,NaN,NaN,NaN,...,96.0,122.0,0.0,7.0,17.43,7.62,13.71,0.0,0.0,4cr

In [14]:
a.shape

(182, 53)

In [21]:
b = a.dropna(axis = 0, how = "any")
b

,Player,COUNTRY,TEAM,AGE,CAPTAINCY EXP,Paying_Role,Mat,Inns,Runs,BF,...,B_TBalls,B_TRuns,B_TMaidens,B_TWkts,B_TAvg,B_TEcon,B_TSR,B_T4w,B_T5w,SOLD_PRICE
1,Shivam Dube,IND,CSK,29,0,All rounder,35,33.0,688.0,516.0,...,129.0,216.0,0.0,5.0,43.20,10.05,25.80,0.0,0.0,4cr
4,Moeen Ali,ENG,CSK,35,0,All rounder,44,42.0,910.0,632.0,...,829.0,1145.0,1.0,42.0,27.26,8.29,19.74,0.0,0.0,8cr
6,Ravindra Jadeja,IND,CSK,34,1,All rounder,210,161.0,2502.0,1960.0,...,1237.0,1453.0,4.0,51.0,28.49,7.05,24.25,0.0,0.0,16cr
9,Dwayne Bravo,WI,CSK,39,0,All rounder,161,113.0,1560.0,1204.0,...,1505.0,2036.0,0.0,78.0,26.10,8.12,19.29,3.0,0.0,4.40cr
10,Mitchell Santner,NZ,CSK,31,0,All rounder,12,6.0,54.0,50.0,...,1718.0,2021.0,2.0,91.0,22.21,7.06,18.88,2.0,0.0,1.90cr
11,Chris Jordan,ENG,CSK,34,0,All rounder,28,11.0,75.0,65.0,...,1804.0,2622.0,2.0,96.0,27.31,8.72,18.79,3.0,0.0,3.60cr
21,Mitchell Marsh,AUS,DC,31,0,All rounder,29,23.0,476.0,386.0,...,264.0,348.0,0.0,15.0,13.20,7.91,17.60,0.0,0.0,6.50cr
23,Axar Patel,IND,DC,29,0,All rounder,122,88.0,1135.0,881.0,...,745.0,929.0,1.0,37.0,25.11,7.48,20.14,0.0,0.0,9cr
25,Shardul Thakur,IND,DC,31,0,All rounder,75,24.0,173.0,134.0,...,506.0,772.0,0.0,33.0,23.39,9.15,15.33,1.0,0.0,10.75cr
35,Hardik Pandya,IND,GT,29,1,All rounder,107,100.0,1963.0,1330.0,...,1347.0,1824.0,1.0,69.0,26.43,8.15,19.46,3.0,0.0,15cr
43,Rashid Khan,AFG,GT,24,0,All rounder,92,43.0,313.0,206.0,...,1754.0,1820.0,1.0,126.0,14.44,6.23,13.92,4.0,2.0,15cr
44,Vijay Shankar,IND,GT,32,0,All rounder,51,43.0,731.0,599.0,...,126.0,191.0,0.0,5.0,38.20,9.10,25.20,0.0,0.0,1.40cr
55,Andre Russell,WI,KKR,34,0,All rounder,98,82.0,2035.0,1144.0,...,891.0,1364.0,0.0,39.0,34.97,9.19,22.85,0.0,0.0,12cr
56,Venkatesh Iyer,IND,KKR,28,0,All rounder,22,22.0,552.0,457.0,...,55.0,75.0,0.0,5.0,15.00,8018.00,11.00,0.0,0.0,8cr
60,Sunil Narine,WI,KKR,34,0,All rounder,148,86.0,1025.0,630.0,...,1102.0,1105.0,1.0,52.0,21.25,6.02,21.19,1.0,0.0,6cr
61,Pat Cummins,AUS,KKR,29,0,All rounder,42,31.0,379.0,249.0,...,1098.0,1350.0,3.0,55.0,24.55,7.38,19.96,0.0,0.0,7.25cr
69,Shivam Mavi,IND,KKR,24,0,All rounder,32,12.0,51.0,56.0,...,84.0,123.0,0.0,7.0,17.57,8.79,12.00,1.0,0.0,7.25cr
75,Deepak Hooda,IND,LSG,27,0,All rounder,95,75.0,1236.0,936.0,...,95.0,76.0,0.0,6.0,12.67,4.80,15.83,1.0,0.0,5.75cr
76,Krunal Pandya,IND,LSG,31,0,All rounder,98,85.0,1326.0,970.0,...,410.0,554.0,1.0,15.0,36.93,8.11,27.33,1.0,0.0,8.25cr
78,Marcus Stoinis,AUS,LSG,33,0,All rounder,67,59.0,1070.0,779.0,...,428.0,614.0,0.0,18.0,34.11,8.61,23.78,0.0,0.0,9.20cr
81,Jason Holder,WI,LSG,31,0,All rounder,38,24.0,247.0,199.0,...,1006.0,1370.0,1.0,51.0,26.86,8.17,19.73,2.0,1.0,8.75cr
99,Daniel Sams,AUS,MI,30,0,All rounder,16,13.0,44.0,44.0,...,180.0,305.0,0.0,7.0,43.57,10.17,25.71,0.0,0.0,2.60cr
100,Sherfane Rutherford,WI,MI,24,0,All rounder,10,9.0,106.0,104.0,...,36.0,49.0,0.0,1.0,49.00,8.17,36.00,0.0,0.0,1cr
103,Fabian Allen,WI,MI,27,0,All rounder,5,4.0,14.0,19.0,...,521.0,646.0,1.0,24.0,26.92,7.44,21.71,0.0,0.0,75l
112,Liam Livingstone,ENG,PK,29,0,All rounder,23,23.0,549.0,329.0,...,300.0,405.0,0.0,15.0,27.00,8.10,20.00,0.0,0.0,11.50cr
119,Odean Smith,WI,PK,26,0,All rounder,6,6.0,51.0,44.0,...,414.0,679.0,0.0,24.0,28.29,9.84,17.25,0.0,0.0,6cr
121,Rishi Dhawan,IND,PK,33,0,All rounder,32,21.0,190.0,175.0,...,24.0,42.0,0.0,1.0,42.00,10.50,24.00,0.0,0.0,55l
134,Glenn Maxwell,AUS,RCB,34,1,All rounder,110,106.0,2309.0,1507.0,...,865.0,1076.0,0.0,39.0,27.59,7.46,22.18,0.0,0.0,11cr
139,Harshal Patel,IND,RCB,32,0,All rounder,78,36.0,230.0,178.0,...,503.0,770.0,0.0,29.0,26.55,9.18,17.34,1.0,0.0,10.75cr
140,Wanindu Hasaranga,SL,RCB,25,0,All rounder,18,9.0,39.0,45.0,...,1186.0,1345.0,1.0,89.0,15.11,6.80,13.33,2.0,0.0,10.75cr
143,David Willey,ENG,RCB,33,0,All rounder,7,2.0,18.0,30.0,...,865.0,1180.0,1.0,51.0,23.14,8.08,16.96,1.0,0.0,2cr
150,Ravichandran Ashwin,IND,RR,36,2,All rounder,184,75.0,647.0,550.0,...,1452.0,1672.0,3.0,72.0,23.22,6.91,20.17,2.0,0.0,5cr
153,Daryl Mitchell,NZ,RR,31,0,All rounder,2,2.0,33.0,44.0,...,89.0,148.0,0.0,8.0,18.50,9.98,11.12,0.0,0.0,75l
154,James Neesham,NZ,RR,32,0,All rounder,14,10.0,92.0,93.0,...,495.0,753.0,0.0,25.0,30.12,9.13,19.80,0.0,0.0,1.50cr
165,Aiden Markram,SA,SRH,28,0,All rounder,20,18.0,527.0,393.0,...,138.0,169.0,2.0,7.0,24.14,7.35,19.71,0.0,0.0,2.60cr
168,Washington Sundar,IND,SRH,23,0,All rounder,51,33.0,318.0,264.0,...,675.0,813.0,1.0,29.0,28.03,7.23,25.28,0.0,0.0,8.75cr
170,Romario Shepherd,WI,SRH,28,0,All rounder,3,3.0,58.0,41.0,...,371.0,650.0,0.0,21.0,30.95,10.51,17.67,0.0,0.0,7.75cr
174,Marco Jansen,SA,SRH,22,0,All rounder,10,5.0,9.0,10.0,...,24.0,38.0,0.0,1.0,38.00,9.50,24.00,0.0,0.0,4.20cr
175,Sean Abbott,AUS,SRH,31,0,All rounder,3,3.0,22.0,18.0,...,138.0,189.0,0.0,5.0,37.80,8.22,27.60,0.0,0.0,2.40cr

In [18]:
a.shape

(39, 53)

Task. 3 :- For the 'runs' column in your IPL player stats DataFrame, use fillna() to replace missing values with the mean of the column. Print the updated column to verify the changes.

In [23]:
a["Runs"]

0      1207.0
1       688.0
2      4190.0
3       252.0
4       910.0
        ...
177     226.0
178       NaN
179       NaN
180      70.0
181       NaN
Name: Runs, Length: 182, dtype: float64

In [25]:
a["Runs"].mean()

np.float64(1058.512)

In [24]:
a["Runs"].fillna(a["Runs"].mean())

0      1207.000
1       688.000
2      4190.000
3       252.000
4       910.000
         ...
177     226.000
178    1058.512
179    1058.512
180      70.000
181    1058.512
Name: Runs, Length: 182, dtype: float64

Task. 4 :- Simulate a Zomato-style restaurant ratings dataset with some missing ratings. Use forward fill (method='ffill') to fill missing values in the ratings column, then use backward fill (method='bfill') for any remaining missing values. Show the before and after results.

In [23]:
z = pd.read_csv(r"C:\PYTHON\Assignments-\Libraries\Session-6\zomato_dataset.csv")
z

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,84,249.0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,45,129.0
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,NaN,39,189.0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,43,189.0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,31,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123652,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Reshmi Kebab,NaN,0,525.0
123653,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Large Tikka,NaN,0,525.0
123654,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Chukandri Tikka,NaN,0,525.0
123655,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Golden Kebab,NaN,0,525.0
123656,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Gosht Gilawat Chop,BESTSELLER,0,595.0

due to high data, I have taken only some random data

In [46]:
c = z["Delivery Rating"].sample(40).head(10)
c

101997    3.7
11083     3.9
93408     3.9
65905     3.8
113913    3.7
64888     NaN
20079     4.0
33045     4.2
55366     NaN
65553     3.7
Name: Delivery Rating, dtype: float64

In [47]:
c.ffill()

101997    3.7
11083     3.9
93408     3.9
65905     3.8
113913    3.7
64888     3.7
20079     4.0
33045     4.2
55366     4.2
65553     3.7
Name: Delivery Rating, dtype: float64

In [48]:
c.bfill()

101997    3.7
11083     3.9
93408     3.9
65905     3.8
113913    3.7
64888     4.0
20079     4.0
33045     4.2
55366     3.7
65553     3.7
Name: Delivery Rating, dtype: float64

Task. 5 :- Pick any one column with missing values from your dataset and explain which missingness mechanism (MCAR, MAR, or MNAR) is most likely and why, using 2-3 sentences.<br><br><em><strong>Hint:</strong> Think about whether the missing data is random or related to other factors in the dataset.</em>

In [49]:
# doubt